trigger:
- master

pr: none

variables:
  HELM_EXPERIMENTAL_OCI: 1
  ACR.Name: 'f2deskacrdev'
  Azure.ServiceConnection: 'F2D-NON-PRD-SVC'

stages:
- stage: build
  condition: false
  displayName: Build and Push
  jobs:  
  - job: job_helm
    displayName: Helm Publish
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: Login to Azure Container Registry
      inputs:
        azureSubscription: "$(Azure.ServiceConnection)"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(ACR.Name)
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - bash: |
         helm package ./azure-vote/azure-vote-front --app-version $(Build.BuildNumber)
         mv *.tgz $(Build.ArtifactStagingDirectory)/
    - task: AzureCLI@1
      displayName: 'Push helm chart'
      inputs:
        azureSubscription: $(Azure.ServiceConnection)
        scriptLocation: inlineScript
        inlineScript: 'helm push $(Build.ArtifactStagingDirectory)/*.tgz oci://f2deskacrdev.azurecr.io/helm'
- stage: Deploy
  condition: true
  displayName: Deploy to aks cluster
  jobs:
  - job: job_helm_deploy
    displayName: Deploy to aks
    pool: 
      name: "f2d-self-hosted-agentpool"
      vmImage: "aewnw02004test"
    steps:
              - task: HelmInstaller@0
                displayName: install helm
                inputs:
                  helmVersion: 'latest'
                  installKubectl: false
              - task: AzureCLI@2
                displayName: Login to Azure Container Registry
                inputs:
                   azureSubscription: "$(Azure.ServiceConnection)"
                   scriptType: bash
                   scriptLocation: inlineScript
                   inlineScript: |
                     USER_NAME="helmtoken"
                     PASSWORD=$(az acr token create -n $USER_NAME -r $ACR_NAME --scope-map _repositories_admin --only-show-errors --query "credentials.passwords[0].value" -o tsv)
                     helm registry login $(acr.name).azurecr.io --username $USER_NAME --password $PASSWORD
                     echo "login to acr using helm"

              - bash: |
                    helm pull oci://$(acr.name).azurecr.io/helm/azure-vote-front --version 0.1.0 -d "$(System.DefaultWorkingDirectory)"
                    echo "get helm chart on agent"
                    echo "$(System.DefaultWorkingDirectory)"
              - task: KubectlInstaller@0
                displayName: Kubectl installer
                inputs: 
                 kubectlVersion: latest

              - task: HelmDeploy@0
                displayName: deploy chart to aks
                inputs:
                  connectionType: 'Azure Resource Manager'
                  azureSubscription: 'F2D-NON-PRD-SVC'
                  azureResourceGroup: 'AZ-F2D-EW-RGP_AKS-sandbox'
                  kubernetesCluster: 'AZ-f2d-WE-QST-N-2004-AKS-Sandbox'
                  azureContainerRegistry: $(ACR.Name)
                  namespace: 'test'
                  command: 'upgrade'
                  chartPath: "$(System.DefaultWorkingDirectory)/azure-vote-front:0.1.0"
                  chartName: "azure-vote-front"             
                  waitForExecution: false
                  releaseName: 'helmdemo'
               